(def collate-test-dir (str (temp-dir) "/collate-fs-changes"))
$(rm -rf $collate-test-dir)
(def collate-test-file0 (str collate-test-dir "/foo0.txt"))
(def collate-test-file1 (str collate-test-dir "/foo1.txt"))
$(mkdir $collate-test-dir)
$(touch $collate-test-file0)
(def collator (collate-fs-changes collate-test-dir))
$(touch $collate-test-file1)
(def changes (collator))
(test::assert-equal (vec collate-test-dir) (hash-get changes :modified))
(test::assert-equal (vec collate-test-file1) (hash-get changes :created))
(test::assert-equal (make-vec) (hash-get changes :deleted))
$(echo "boop" >> $collate-test-file0)
(set! changes (collator))
(test::assert-equal (vec collate-test-file0) (hash-get changes :modified))
(test::assert-equal (make-vec) (hash-get changes :deleted))
(test::assert-equal (make-vec) (hash-get changes :created))
$(rm -rf $collate-test-dir)
(set! changes (collator))
(test::assert-equal (make-vec) (hash-get changes :created))
(test::assert-equal (make-vec) (hash-get changes :modified))
(def del-items (hash-get changes :deleted))
(test::assert-equal 3 (length del-items))
(test::assert-includes collate-test-dir del-items)
(test::assert-includes collate-test-file0 del-items)
(test::assert-includes collate-test-file1 del-items)
