[book]
authors = ["gpwclark", "sstanfield"]
language = "en"
multilingual = false
src = "src"
title = "Slosh Documentation"

[preprocessor.slosh-eval]
after = ["links"]
doc-forms = true
user-doc-forms = true
doc-supplementary = true
code-block-label = "slosh"
