#!/usr/bin/env slosh

;; Dynamic Environment File Generator
;; This demonstrates generating dynamic env files for systemd

(def *custom-type* "production")
(def *app-version* "1.0.0")

(defn generate-env-file [path]
  "Generate a dynamic environment file at the given path"
  (let [content (str "# Generated by slosh at " (current-time-millis) "\n"
                     "HOST=" (or (env "HOSTNAME") "localhost") "\n"
                     "CUSTOM_TYPE=" *custom-type* "\n"
                     "APP_VERSION=" *app-version* "\n"
                     "USER=" (env "USER") "\n"
                     "PATH=" (env "PATH") "\n")]
    (fs-write path content)
    (println "Generated" path "with content:")
    (println content)))

;; Example usage
(def env-file-path "/tmp/my-service.env")
(generate-env-file env-file-path)

;; Function to create a background process that updates the file periodically
(defn start-dynamic-env-updater [path interval-ms]
  "Start a background process that updates the env file every interval-ms milliseconds"
  (fork 
    (loop []
      (generate-env-file path)
      (sleep interval-ms)
      (recur))))

;; Start updating the file every 5 seconds
(def updater-proc (start-dynamic-env-updater env-file-path 5000))
(println "Started background updater process:" updater-proc)
(println "File will be updated every 5 seconds")
(println "Kill the process with: (kill" (pid updater-proc) "9)")