#!/usr/bin/env slosh

;; Test FUSE dynamic files for systemd environment
;; This demonstrates how to create dynamic environment files

;; Set some global variables that will be used in the env file
(def *custom-type* "production")
(def *app-version* "1.2.3")

;; Mount the dynamic filesystem
(println "Mounting dynamic filesystem...")
(def mount-id (mount-eval-fs "/tmp/slosh-systemd-test"))

;; Register a systemd-style environment file with dynamic content
(println "Registering my-service.env...")
(register-eval-file mount-id "my-service.env"
  "(str \"# Generated by slosh\\n\"
        \"HOST=\" (or (env \"HOSTNAME\") \"meow\") \"\\n\"
        \"CUSTOM_TYPE=\" *custom-type* \"\\n\"
        \"APP_VERSION=\" *app-version* \"\\n\"
        \"USER=\" (env \"USER\") \"\\n\"
        \"HOME=\" (env \"HOME\") \"\\n\")")

;; Register another file for database config
(register-eval-file mount-id "database.env"
  "(str \"DB_HOST=localhost\\n\"
        \"DB_PORT=5432\\n\"
        \"DB_NAME=\" *custom-type* \"_db\\n\"
        \"DB_USER=\" (env \"USER\") \"_app\\n\")")

;; List all registered files
(println "\nRegistered files:")
(doseq [file (list-eval-files mount-id)]
  (println "  -" file))

;; Show what the content would look like when evaluated
(println "\n--- Testing file evaluation ---")
(println "my-service.env would contain:")
(println (eval-file-expression mount-id "my-service.env"))

(println "\ndatabase.env would contain:")
(println (eval-file-expression mount-id "database.env"))

;; Change a global variable and show how it affects the file
(println "\n--- Changing *custom-type* to 'development' ---")
(set! *custom-type* "development")

(println "my-service.env now contains:")
(println (eval-file-expression mount-id "my-service.env"))

(println "\ndatabase.env now contains:")
(println (eval-file-expression mount-id "database.env"))

;; Clean up
(unmount-eval-fs mount-id)
(println "\nFilesystem unmounted.")
(println "\nIn a real implementation, these files would be accessible at:")
(println "  /tmp/slosh-systemd-test/my-service.env")
(println "  /tmp/slosh-systemd-test/database.env")
(println "And systemd could read them directly!")